// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SqliteAdapter;
using System;

namespace SqliteAdapter.Migrations
{
    [DbContext(typeof(RnvScotlandYardContext))]
    [Migration("20171029113516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SqliteAdapter.GameSessionDb", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MrxId");

                    b.HasKey("GameSessionId");

                    b.HasIndex("MrxId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SqliteAdapter.MovementsDb", b =>
                {
                    b.Property<string>("MovementId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromStationId");

                    b.Property<string>("ToStationId");

                    b.Property<int>("VehicleTypeId");

                    b.HasKey("MovementId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("SqliteAdapter.MrxDb", b =>
                {
                    b.Property<string>("MrxId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("TicketPoolId");

                    b.HasKey("MrxId");

                    b.HasIndex("TicketPoolId");

                    b.ToTable("MrXs");
                });

            modelBuilder.Entity("SqliteAdapter.PoliceOfficerDb", b =>
                {
                    b.Property<string>("PoliceOfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameSessionDbGameSessionId");

                    b.Property<string>("GameSessionId");

                    b.Property<string>("Name");

                    b.Property<string>("TicketPoolId");

                    b.HasKey("PoliceOfficerId");

                    b.HasIndex("GameSessionDbGameSessionId");

                    b.HasIndex("TicketPoolId");

                    b.ToTable("PoliceOfficers");
                });

            modelBuilder.Entity("SqliteAdapter.TicketPoolDb", b =>
                {
                    b.Property<string>("TicketPoolId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("TicketPoolId");

                    b.ToTable("TicketPools");
                });

            modelBuilder.Entity("SqliteAdapter.VehicleTypeDb", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VehicleType");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("SqliteAdapter.GameSessionDb", b =>
                {
                    b.HasOne("SqliteAdapter.MrxDb", "Mrx")
                        .WithMany()
                        .HasForeignKey("MrxId");
                });

            modelBuilder.Entity("SqliteAdapter.MovementsDb", b =>
                {
                    b.HasOne("SqliteAdapter.VehicleTypeDb", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SqliteAdapter.MrxDb", b =>
                {
                    b.HasOne("SqliteAdapter.TicketPoolDb", "TicketPoolDb")
                        .WithMany()
                        .HasForeignKey("TicketPoolId");
                });

            modelBuilder.Entity("SqliteAdapter.PoliceOfficerDb", b =>
                {
                    b.HasOne("SqliteAdapter.GameSessionDb", "GameSessionDb")
                        .WithMany("PosPoliceOfficersts")
                        .HasForeignKey("GameSessionDbGameSessionId");

                    b.HasOne("SqliteAdapter.TicketPoolDb", "TicketPoolDb")
                        .WithMany()
                        .HasForeignKey("TicketPoolId");
                });
#pragma warning restore 612, 618
        }
    }
}
