// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SqliteAdapter.Model;
using System;

namespace SqliteAdapter.Migrations
{
    [DbContext(typeof(RnvScotlandYardContext))]
    [Migration("20171111140509_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SqliteAdapter.Model.GameSessionDb", b =>
                {
                    b.Property<string>("GameSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxPoliceOfficers");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("StartTime");

                    b.HasKey("GameSessionId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MoveMrXDb", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MrxDbMrxId");

                    b.Property<string>("StationId");

                    b.Property<string>("VehicleType");

                    b.HasKey("MoveId");

                    b.HasIndex("MrxDbMrxId");

                    b.ToTable("MoveMrX");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MovePoliceOfficerDb", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PoliceOfficerDbPoliceOfficerId");

                    b.Property<string>("StationId");

                    b.Property<string>("VehicleType");

                    b.HasKey("MoveId");

                    b.HasIndex("PoliceOfficerDbPoliceOfficerId");

                    b.ToTable("MovePoliceOfficers");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MrxDb", b =>
                {
                    b.Property<string>("MrxId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameSessionDbId");

                    b.Property<string>("LastKnownStation");

                    b.Property<string>("Name");

                    b.HasKey("MrxId");

                    b.HasIndex("GameSessionDbId")
                        .IsUnique();

                    b.ToTable("MrXs");
                });

            modelBuilder.Entity("SqliteAdapter.Model.OpenMoveMrxDb", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MrxDbMrxId");

                    b.Property<string>("StationId");

                    b.Property<string>("VehicleType");

                    b.HasKey("MoveId");

                    b.HasIndex("MrxDbMrxId");

                    b.ToTable("OpenMoveMrx");
                });

            modelBuilder.Entity("SqliteAdapter.Model.PoliceOfficerDb", b =>
                {
                    b.Property<string>("PoliceOfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentStationId");

                    b.Property<string>("GameSessionDbId");

                    b.Property<string>("Name");

                    b.HasKey("PoliceOfficerId");

                    b.HasIndex("GameSessionDbId");

                    b.ToTable("PoliceOfficers");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MoveMrXDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.MrxDb")
                        .WithMany("MoveHistory")
                        .HasForeignKey("MrxDbMrxId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MovePoliceOfficerDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.PoliceOfficerDb")
                        .WithMany("MoveHistory")
                        .HasForeignKey("PoliceOfficerDbPoliceOfficerId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MrxDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.GameSessionDb")
                        .WithOne("Mrx")
                        .HasForeignKey("SqliteAdapter.Model.MrxDb", "GameSessionDbId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.OpenMoveMrxDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.MrxDb")
                        .WithMany("OpenMoves")
                        .HasForeignKey("MrxDbMrxId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.PoliceOfficerDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.GameSessionDb", "GameSessionDb")
                        .WithMany("PoliceOfficers")
                        .HasForeignKey("GameSessionDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
