// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SqliteAdapter.Model;
using System;

namespace SqliteAdapter.Migrations
{
    [DbContext(typeof(RnvScotlandYardContext))]
    partial class RnvScotlandYardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SqliteAdapter.Model.GameSessionDb", b =>
                {
                    b.Property<string>("GameSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("StartTime");

                    b.HasKey("GameSessionId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MovementsDb", b =>
                {
                    b.Property<string>("MovementId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromStationId");

                    b.Property<string>("ToStationId");

                    b.Property<string>("VehicleTypeId");

                    b.HasKey("MovementId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MrxDb", b =>
                {
                    b.Property<string>("MrxId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameSessionDbId");

                    b.Property<string>("Name");

                    b.HasKey("MrxId");

                    b.HasIndex("GameSessionDbId")
                        .IsUnique();

                    b.ToTable("MrXs");
                });

            modelBuilder.Entity("SqliteAdapter.Model.PoliceOfficerDb", b =>
                {
                    b.Property<string>("PoliceOfficerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameSessionDbId");

                    b.Property<string>("Name");

                    b.HasKey("PoliceOfficerId");

                    b.HasIndex("GameSessionDbId");

                    b.ToTable("PoliceOfficers");
                });

            modelBuilder.Entity("SqliteAdapter.Model.VehicleTypeDb", b =>
                {
                    b.Property<string>("VehicleTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VehicleType");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MovementsDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.VehicleTypeDb", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.MrxDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.GameSessionDb")
                        .WithOne("Mrx")
                        .HasForeignKey("SqliteAdapter.Model.MrxDb", "GameSessionDbId");
                });

            modelBuilder.Entity("SqliteAdapter.Model.PoliceOfficerDb", b =>
                {
                    b.HasOne("SqliteAdapter.Model.GameSessionDb", "GameSessionDb")
                        .WithMany("PoliceOfficers")
                        .HasForeignKey("GameSessionDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
